creation_rules:
  - path_regex: secrets.yaml
    key_groups:
      - age:
          - age1ys25qhz9va7cth5tk0m57njhyw4y4fe2xyeh747wk2p4gjrm8u5s4uh9ke
          - age1029tun5wzydc95qznhwaxfnwd6dhaerwu7j0kype8s4h432nhp0s0utxdm
